# Generated by Django 6.0.4 on 2026-04-11 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portefolio", "0002_docente"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("ano", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("imagem", models.ImageField(upload_to="ucs/")),
                ("docentes", models.ManyToManyField(to="portefolio.docente")),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portefolio.licenciatura",
                    ),
                ),
            ],
        ),
    ]
