# Generated by Django 6.0.4 on 2026-04-11 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portefolio", "0004_competencia_tecnologia_projeto"),
    ]

    operations = [
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("ano", models.CharField(max_length=20)),
                ("licenciatura", models.CharField(max_length=200)),
                ("sumario", models.TextField()),
                ("link_pdf", models.URLField(blank=True, null=True)),
                ("imagem", models.URLField(blank=True, null=True)),
                ("palavras_chave", models.TextField(blank=True)),
                ("areas", models.TextField(blank=True)),
                ("tecnologias", models.TextField(blank=True)),
                ("rating", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ExperienciaProfissional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=100)),
                ("cargo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("aprendizagem", models.TextField()),
                ("competencias", models.ManyToManyField(to="portefolio.competencia")),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("instituicao", models.CharField(max_length=100)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("descricao", models.TextField()),
                ("competencias", models.ManyToManyField(to="portefolio.competencia")),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
                ("data", models.DateField()),
                ("imagem", models.ImageField(upload_to="makingof/")),
                ("decisao", models.TextField()),
                ("erro", models.TextField()),
                ("correcao", models.TextField()),
                (
                    "projeto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portefolio.projeto",
                    ),
                ),
                (
                    "tecnologia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portefolio.tecnologia",
                    ),
                ),
                (
                    "unidade_curricular",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portefolio.unidadecurricular",
                    ),
                ),
            ],
        ),
    ]
